project:
  type: book
  preview:
    watch-inputs: true
  resources:
    - "fonts/"
    - main.css

book:
  favicon: favicon.png
  title: "Database and MySQL Handbook"
  description: "A handbook to quickly understand Relational Databases and the basics of SQL with MySQL"
  site-url: https://brin.is-a.dev/db-mysql-handbook/
  author: 
    - name: "Trinethr N"
      email: 'trinethr_n@yahoo.com'
      url: 'https://brin.is-a.dev'
  chapters:
    - index.qmd
    - intro.qmd
    - sql.qmd
    - dbcreate.qmd
    - datatypes.qmd
    - tables.qmd
    - datamanip.qmd
    - simple-queries.qmd
    - table-queries.qmd
    - joins.qmd
    - afterword.qmd
  sidebar:
    logo: 
      light: icon.png
      dark: icon-dark.png
  image: banner.png
  twitter-card: 
    card-style: summary_large_image
  open-graph: 
    locale: en_US


format:
  html:
    theme: 
      light: flatly
      dark: darkly
    respect-user-color-scheme: true
    highlight-style:
      light: arrow
      dark: atom-one-dark
    mainfont: "Arial"
    monofont: "0xProto"
    css: main.css
    

  pdf:
    documentclass: scrbook
    classoption: [openany]
    toc: true
    number-sections: true

    code-overflow: wrap
    tbl-colwidths: auto

    sansfont: "Arial"
    mainfont: "Arial"
    mainfontoptions:
      - BoldFont='Arial Bold'
      - ItalicFont='Arial Italic'
      - BoldItalicFont='Arial Bold Italic'
    monofont: "0xProto"
    geometry:
      - top=25mm
      - bottom=30mm
      - left=20mm
      - right=20mm
      - headheight=15pt
    include-in-header:
      text: |
        \usepackage{fvextra}
        \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
        \RedeclareSectionCommand[beforeskip=10pt]{chapter}
        \RedeclareSectionCommand[beforeskip=-2ex, afterskip=1ex]{section}
        \RedeclareSectionCommand[beforeskip=-1.5ex, afterskip=0.5ex]{subsection}