project:
  type: book
  preview:
    watch-inputs: true

book:
  favicon: favicon.png
  title: "Database and MySQL Handbook"
  author: 
    - name: "Trinethr N"
      email: 'trinethr_n@yahoo.com'
      url: 'https://brin.is-a.dev'
  chapters:
    - index.qmd
    - intro.qmd
    - sql.qmd
    - dbcreate.qmd
    - datatypes.qmd
    - tables.qmd
    - datamanip.qmd
    - simple-queries.qmd
    - table-queries.qmd
    - joins.qmd
    - afterword.qmd

format:
  html:
    theme: flatly
    mainfont: "Arial"
    monofont: "0xProto"
    css: main.css
    cover-image: icon.png

  pdf:
    documentclass: scrbook
    classoption: [openany]
    toc: true
    number-sections: true

    code-overflow: wrap
    tbl-colwidths: auto

    sansfont: "Arial"
    mainfont: "Arial"
    mainfontoptions:
      - BoldFont='Arial Bold'
      - ItalicFont='Arial Italic'
      - BoldItalicFont='Arial Bold Italic'
    monofont: "0xProto"
    geometry:
      - top=25mm
      - bottom=30mm
      - left=20mm
      - right=20mm
      - headheight=15pt
    include-in-header:
      text: |
        \usepackage{fvextra}
        \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
        \RedeclareSectionCommand[beforeskip=10pt]{chapter}
        \RedeclareSectionCommand[beforeskip=-2ex, afterskip=1ex]{section}
        \RedeclareSectionCommand[beforeskip=-1.5ex, afterskip=0.5ex]{subsection}