# Preface {.unnumbered}

This book was written with an aim to explain the concepts of Database Management with MySQL, according to the CBSE Syllabus, in a concise manner with good flow of topics. 

It introduces the concept of databases, explaining its advantages over traditional data storage systems, and explains the relational database model. Following this is a comprehensive guide to working with MySQL - including creating databases and tables, adding data, and fetching data with queries.

## Disclaimer

This document has been written in accordance to the [2025-26 CBSE Senior Secondary Computer Science Syllabus](https://cbseacademic.nic.in/web_material/CurriculumMain26/SrSec/Computer_Science_SrSec_2025-26.pdf), to cover topics in *Unit 3: Database Management* (**except 'interfacing an SQL database with Python'**), however it should be used as a supplementary resource alongside the prescribed textbook and other study materials.

## AI Usage Disclosure

*AI tools have been used to edit some parts of the book, such as some examples and descriptions, to enhance their clarity and structure.*

## Feedback
You can write your feedback regarding the handbook to me at <trinethr_n@yahoo.com>. Alternatively, if you have corrections or suggestions that you would like to implement, fork the github repository at [brinterwastaken/db-mysql-handbook](https://github.com/brinterwastaken/db-mysql-handbook) and open a pull request.